workflows:
  ios-workflow:
    name: iOS -> TestFlight (unique build number)
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - panna

      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.panna.signalsApp

      vars:
        BUILD_NAME: "1.0.2"

    scripts:
      - name: Print repo + current pubspec version
        script: |
          set -euo pipefail
          echo "GIT:"
          git rev-parse --short HEAD || true
          echo "pubspec version:"
          grep -n "^version:" pubspec.yaml || true

      - name: Get Flutter packages
        script: |
          set -euo pipefail
          flutter pub get

      - name: Install Pods
        script: |
          set -euo pipefail
          cd ios
          pod install
          cd ..

      - name: Decode App Store Connect key (B64 -> AuthKey.p8)
        script: |
          set -euo pipefail
          echo "B64 length: ${#APP_STORE_CONNECT_PUBLISHER_PRIVATE_KEY_B64}"
          [ -z "${APP_STORE_CONNECT_PUBLISHER_PRIVATE_KEY_B64:-}" ] && echo "B64 missing ❌" && exit 1
          echo "$APP_STORE_CONNECT_PUBLISHER_PRIVATE_KEY_B64" | base64 --decode > AuthKey.p8
          ls -la AuthKey.p8
          grep -q "BEGIN PRIVATE KEY" AuthKey.p8 && echo "BEGIN OK ✅" || (echo "BEGIN missing ❌" && exit 1)
          grep -q "END PRIVATE KEY" AuthKey.p8 && echo "END OK ✅" || (echo "END missing ❌" && exit 1)

      - name: Force unique iOS build/version (AGVTOOL + plist + pubspec)
        script: |
          set -euo pipefail

          # Always-unique build number (UTC): YYYYMMDDHHMMSS
          BUILD_NUMBER="$(date -u +%Y%m%d%H%M%S)"
          echo "FORCING BUILD_NAME=$BUILD_NAME"
          echo "FORCING BUILD_NUMBER=$BUILD_NUMBER"

          # Persist BUILD_NUMBER for next steps
          echo "BUILD_NUMBER=$BUILD_NUMBER" >> $CM_ENV

          # 1) pubspec.yaml version (so Flutter side is consistent)
          perl -0777 -i -pe 's/^version:\s*.+$/version: '"$BUILD_NAME"'+'"$BUILD_NUMBER"'/m' pubspec.yaml
          echo "pubspec version now:"
          grep '^version:' pubspec.yaml || true

          # 2) Xcode-native versioning (strongest)
          cd ios
          agvtool new-version -all "$BUILD_NUMBER"
          agvtool new-marketing-version "$BUILD_NAME"
          cd ..

          # 3) Info.plist (extra safety)
          PLIST="ios/Runner/Info.plist"
          /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $BUILD_NAME" "$PLIST" 2>/dev/null \
            || /usr/libexec/PlistBuddy -c "Add :CFBundleShortVersionString string $BUILD_NAME" "$PLIST"
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" "$PLIST" 2>/dev/null \
            || /usr/libexec/PlistBuddy -c "Add :CFBundleVersion string $BUILD_NUMBER" "$PLIST"

          echo "Info.plist now:"
          /usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "$PLIST"
          /usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "$PLIST"

      - name: Set up code signing settings on Xcode project
        script: |
          set -euo pipefail
          xcode-project use-profiles --project ios/Runner.xcodeproj --archive-method app-store
          echo "export_options.plist:"
          ls -la "$HOME/export_options.plist" || true

      - name: Build IPA + Verify CFBundleVersion inside IPA
        script: |
          set -euo pipefail
          echo "Using BUILD_NAME=$BUILD_NAME BUILD_NUMBER=$BUILD_NUMBER"

          flutter clean
          flutter pub get

          # Build IPA (don't rely on flutter flags changing by version)
          flutter build ipa

          echo "=== IPA proof (read CFBundleVersion from IPA) ==="
          IPA_PATH="$(ls -1 build/ios/ipa/*.ipa | head -n 1)"
          echo "IPA: $IPA_PATH"

          TMP_DIR="$(mktemp -d)"
          unzip -q "$IPA_PATH" -d "$TMP_DIR"
          PLIST="$TMP_DIR/Payload/Runner.app/Info.plist"

          echo "CFBundleShortVersionString:"
          /usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "$PLIST"
          echo "CFBundleVersion:"
          /usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "$PLIST"

          ACTUAL_BUNDLE_VERSION="$(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "$PLIST" | tr -d '\r')"
          if [ "$ACTUAL_BUNDLE_VERSION" != "$BUILD_NUMBER" ]; then
            echo "❌ Build number NOT applied! expected=$BUILD_NUMBER got=$ACTUAL_BUNDLE_VERSION"
            exit 1
          fi
          echo "✅ Build number applied correctly: $ACTUAL_BUNDLE_VERSION"

      - name: Upload IPA to App Store Connect (TestFlight)
        script: |
          set -euo pipefail

          IPA_PATH="$(ls -1 build/ios/ipa/*.ipa | head -n 1)"
          echo "Uploading: $IPA_PATH"

          app-store-connect publish \
            --path "$IPA_PATH" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --private-key @file:AuthKey.p8

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log


  android-workflow:
    name: Android Workflow
    max_build_duration: 60

    environment:
      flutter: stable
      java: 17

      android_signing:
        - pannasignals_keystore

      groups:
        - google_play

      vars:
        PACKAGE_NAME: "com.panna.signalsApp"
        BUILD_NAME: "1.0.2"
        BUILD_NUMBER: "4"

    scripts:
      - name: Set up key.properties
        script: |
          echo "storePassword=pannaSignals2024" > $CM_BUILD_DIR/android/key.properties
          echo "keyPassword=pannaSignals2024" >> $CM_BUILD_DIR/android/key.properties
          echo "keyAlias=upload" >> $CM_BUILD_DIR/android/key.properties
          echo "storeFile=$CM_KEYSTORE_PATH" >> $CM_BUILD_DIR/android/key.properties

      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Build AAB
        script: |
          flutter clean
          flutter build appbundle --release \
            --build-name=$BUILD_NAME \
            --build-number=$BUILD_NUMBER

    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log

    publishing:
      email:
        recipients:
          - driton.mahmudi@gmail.com
        notify:
          success: true
          failure: true

      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true
