workflows:
  ios-workflow:
    name: iOS -> TestFlight
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

      groups:
        - panna

      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.panna.signalsApp

      vars:
        BUILD_NAME: "1.0.2"

    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Install Pods
        script: |
          cd ios
          pod install
          cd ..

      - name: Decode App Store Connect key (B64 -> AuthKey.p8)
        script: |
          set -e
          echo "B64 length: ${#APP_STORE_CONNECT_PUBLISHER_PRIVATE_KEY_B64}"
          [ -z "$APP_STORE_CONNECT_PUBLISHER_PRIVATE_KEY_B64" ] && echo "B64 missing ❌" && exit 1

          echo "$APP_STORE_CONNECT_PUBLISHER_PRIVATE_KEY_B64" | base64 --decode > AuthKey.p8
          ls -la AuthKey.p8

          grep -q "BEGIN PRIVATE KEY" AuthKey.p8 && echo "BEGIN OK ✅" || (echo "BEGIN missing ❌" && exit 1)
          grep -q "END PRIVATE KEY" AuthKey.p8 && echo "END OK ✅" || (echo "END missing ❌" && exit 1)

      - name: Export App Store Connect private key for publishing
        script: |
          set -e
          export APP_STORE_CONNECT_PUBLISHER_PRIVATE_KEY="$(cat AuthKey.p8)"
          echo "PRIVATE_KEY length: ${#APP_STORE_CONNECT_PUBLISHER_PRIVATE_KEY}"
          echo "$APP_STORE_CONNECT_PUBLISHER_PRIVATE_KEY" | grep -q "BEGIN PRIVATE KEY" && echo "BEGIN OK ✅" || (echo "BEGIN missing ❌" && exit 1)

      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles --project ios/Runner.xcodeproj --archive-method app-store

      - name: Build IPA (unique build number)
        script: |
          set -e

          BUILD_NUMBER="$(date +%Y%m%d%H%M%S)"
          echo "Using BUILD_NAME=$BUILD_NAME BUILD_NUMBER=$BUILD_NUMBER"

          flutter clean
          flutter pub get

          flutter build ipa \
            --release \
            --build-name="$BUILD_NAME" \
            --build-number="$BUILD_NUMBER"

          echo "=== Archive Info.plist proof ==="
          /usr/libexec/PlistBuddy -c "Print :ApplicationProperties:CFBundleShortVersionString" build/ios/archive/Runner.xcarchive/Info.plist || true
          /usr/libexec/PlistBuddy -c "Print :ApplicationProperties:CFBundleVersion" build/ios/archive/Runner.xcarchive/Info.plist || true

      - name: Verify IPA exists
        script: |
          ls -la build/ios/ipa || true
          ls -la build/ios/ipa/*.ipa || true

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        private_key: $APP_STORE_CONNECT_PUBLISHER_PRIVATE_KEY
        submit_to_testflight: true


  android-workflow:
    name: Android Workflow
    max_build_duration: 60

    environment:
      flutter: stable
      java: 17

      android_signing:
        - pannasignals_keystore

      groups:
        - google_play

      vars:
        PACKAGE_NAME: "com.panna.signalsApp"
        BUILD_NAME: "1.0.2"
        BUILD_NUMBER: "4"

    scripts:
      - name: Set up key.properties
        script: |
          echo "storePassword=pannaSignals2024" > $CM_BUILD_DIR/android/key.properties
          echo "keyPassword=pannaSignals2024" >> $CM_BUILD_DIR/android/key.properties
          echo "keyAlias=upload" >> $CM_BUILD_DIR/android/key.properties
          echo "storeFile=$CM_KEYSTORE_PATH" >> $CM_BUILD_DIR/android/key.properties

      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Build AAB
        script: |
          flutter clean
          flutter build appbundle --release \
            --build-name=$BUILD_NAME \
            --build-number=$BUILD_NUMBER

    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log

    publishing:
      email:
        recipients:
          - driton.mahmudi@gmail.com
        notify:
          success: true
          failure: true

      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true
