workflows:
  ios-workflow:
    name: iOS -> TestFlight
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - panna

      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.panna.signalsApp

      vars:
        BUNDLE_ID: "com.panna.signalsApp"
        BUILD_NAME: "1.0.2"
        BUILD_NUMBER: "4" # fallback (do të mbishkruhet automatikisht)

    scripts:
      - name: Verify bundle id in project (debug helper)
        script: |
          echo "=== PRODUCT_BUNDLE_IDENTIFIER (project.pbxproj) ==="
          grep -n "PRODUCT_BUNDLE_IDENTIFIER" ios/Runner.xcodeproj/project.pbxproj | head -n 30
          echo "=== Searching com.example in ios folder (should be empty) ==="
          grep -R "com.example" -n ios | head -n 20 || true

      - name: Fetch signing files (App Store) + apply profiles
        script: |
          keychain initialize

          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --create \
            --type IOS_APP_STORE \
            --platform IOS \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key @env:APP_STORE_CONNECT_PRIVATE_KEY \
            --certificate-key @env:CERTIFICATE_PRIVATE_KEY

          keychain add-certificates
          xcode-project use-profiles --project ios/Runner.xcodeproj --archive-method app-store

      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Install Pods
        script: |
          cd ios
          pod install
          cd ..

      - name: Set unique build number (avoid duplicate uploads)
        script: |
          BUILD_NUMBER=$(date +%Y%m%d%H%M)
          echo "BUILD_NUMBER=$BUILD_NUMBER" >> "$CM_ENV"
          echo "Using BUILD_NAME=$BUILD_NAME BUILD_NUMBER=$BUILD_NUMBER"

      - name: Set version in pubspec.yaml
        script: |
          python3 - << 'PY'
          import re, pathlib, os
          p = pathlib.Path("pubspec.yaml")
          txt = p.read_text(encoding="utf-8")
          build_name = os.environ.get("BUILD_NAME", "1.0.2")
          build_number = os.environ.get("BUILD_NUMBER", "4")
          txt2 = re.sub(r'^version:\s*.*$', f'version: {build_name}+{build_number}', txt, flags=re.M)
          p.write_text(txt2, encoding="utf-8")
          print("✅ pubspec.yaml version set to:", f"{build_name}+{build_number}")
          PY
          grep -n "^version:" pubspec.yaml || true

      - name: Create export_options.plist
        script: |
          cat > export_options.plist <<'PLIST'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>signingStyle</key>
            <string>automatic</string>
            <key>uploadBitcode</key>
            <false/>
            <key>compileBitcode</key>
            <false/>
            <key>stripSwiftSymbols</key>
            <true/>
          </dict>
          </plist>
          PLIST
          echo "✅ export_options.plist created:"
          ls -la export_options.plist

      - name: Build IPA (App Store)
        script: |
          flutter clean
          flutter pub get
          flutter build ipa --export-options-plist=export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log

    publishing:
      email:
        recipients:
          - driton.mahmudi@gmail.com
        notify:
          success: true
          failure: true

      app_store_connect:
        api_key: $APP_STORE_CONNECT_PUBLISHER_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true

  android-workflow:
    name: Android Workflow
    max_build_duration: 60

    environment:
      flutter: stable
      java: 17

      android_signing:
        - pannasignals_keystore

      groups:
        - google_play

      vars:
        PACKAGE_NAME: "com.panna.signalsApp"
        BUILD_NAME: "1.0.2"
        BUILD_NUMBER: "4"

    scripts:
      - name: Set up key.properties
        script: |
          echo "storePassword=pannaSignals2024" > $CM_BUILD_DIR/android/key.properties
          echo "keyPassword=pannaSignals2024" >> $CM_BUILD_DIR/android/key.properties
          echo "keyAlias=upload" >> $CM_BUILD_DIR/android/key.properties
          echo "storeFile=$CM_KEYSTORE_PATH" >> $CM_BUILD_DIR/android/key.properties

      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Build AAB
        script: |
          flutter clean
          flutter build appbundle --release \
            --build-name=$BUILD_NAME \
            --build-number=$BUILD_NUMBER

    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log

    publishing:
      email:
        recipients:
          - driton.mahmudi@gmail.com
        notify:
          success: true
          failure: true

      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true
