workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.pannasignals.app
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.pannasignals.app"
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --build-name=1.0.2 \
            --build-number=3 \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - driton.mahmudi@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true

  android-workflow:
    name: Android Workflow  
    max_build_duration: 60
    environment:
      android_signing:
        - pannasignals_keystore
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.pannasignals.app"
      flutter: stable
      java: 17
    scripts:
      - name: Set up key.properties
        script: |
          echo "storePassword=pannaSignals2024" > $CM_BUILD_DIR/android/key.properties
          echo "keyPassword=pannaSignals2024" >> $CM_BUILD_DIR/android/key.properties
          echo "keyAlias=upload" >> $CM_BUILD_DIR/android/key.properties
          echo "storeFile=$CM_KEYSTORE_PATH" >> $CM_BUILD_DIR/android/key.properties
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build AAB
        script: |
          flutter build appbundle --release \
            --build-name=1.0.2 \
            --build-number=3
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - driton.mahmudi@gmail.com
        notify:
          success: true
          failure: true
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true
