workflows:
  ios-workflow:
    name: iOS -> TestFlight (unique build number)
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - panna

      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.panna.signalsApp

      vars:
        BUILD_NAME: "1.0.2"

    scripts:
      - name: Prepare + Importo certifikatën (.p12) në keychain (fixed)
        script: |
          set -euo pipefail
          export LANG=en_US.UTF-8

          # Trim CR/LF (shpesh shkakton MAC verification failed)
          P12_B64="$(printf %s "${P12_BASE64:-}" | tr -d '\r\n')"
          P12_PASSWORD="$(printf %s "${CERTIFICATE_KEY_PASSWORD:-}" | tr -d '\r\n')"

          echo "P12_BASE64 length: ${#P12_B64}"
          echo "CERTIFICATE_KEY_PASSWORD length: ${#P12_PASSWORD}"

          [ -z "$P12_B64" ] && echo "❌ P12_BASE64 mungon" && exit 1

          rm -f AppleDistribution.p12

          # Decode (macOS)
          (printf "%s" "$P12_B64" | base64 -D > AppleDistribution.p12 2>/dev/null) || \
          (printf "%s" "$P12_B64" | base64 -d > AppleDistribution.p12 2>/dev/null) || \
          (printf "%s" "$P12_B64" | base64 --decode > AppleDistribution.p12)

          [ ! -s AppleDistribution.p12 ] && echo "❌ AppleDistribution.p12 doli bosh" && exit 1

          # Validate P12 (nëse këtu OK, file+password janë OK)
          openssl pkcs12 -in AppleDistribution.p12 -noout -passin pass:"$P12_PASSWORD" >/dev/null
          echo "P12 validate OK ✅"

          # Use Codemagic keychain tool (më stabile se security import)
          pip3 install --user --upgrade codemagic-cli-tools
          export PATH="$(python3 -m site --user-base)/bin:$PATH"

          keychain initialize
          keychain add-certificates --certificate AppleDistribution.p12 --certificate-password "$P12_PASSWORD"
          echo "Keychain import OK ✅"

      - name: Print repo + current pubspec version
        script: |
          set -euo pipefail
          echo "GIT:"
          git rev-parse --short HEAD || true
          echo "pubspec version:"
          grep -n "^version:" pubspec.yaml || true

      - name: Get Flutter packages
        script: |
          set -euo pipefail
          flutter pub get

      - name: Install Pods
        script: |
          set -euo pipefail
          cd ios
          pod install
          cd ..

      - name: Decode App Store Connect key (B64 -> $HOME/AuthKey.p8)
        script: |
          set -euo pipefail
          echo "B64 length: ${#APP_STORE_CONNECT_PUBLISHER_PRIVATE_KEY_B64}"
          [ -z "${APP_STORE_CONNECT_PUBLISHER_PRIVATE_KEY_B64:-}" ] && echo "B64 missing ❌" && exit 1

          (echo "$APP_STORE_CONNECT_PUBLISHER_PRIVATE_KEY_B64" | base64 --decode > "$HOME/AuthKey.p8") || \
          (echo "$APP_STORE_CONNECT_PUBLISHER_PRIVATE_KEY_B64" | base64 -d > "$HOME/AuthKey.p8")

          ls -la "$HOME/AuthKey.p8"
          grep -q "BEGIN PRIVATE KEY" "$HOME/AuthKey.p8" && echo "BEGIN OK ✅" || (echo "BEGIN missing ❌" && exit 1)
          grep -q "END PRIVATE KEY" "$HOME/AuthKey.p8" && echo "END OK ✅" || (echo "END missing ❌" && exit 1)

      - name: Force unique iOS build/version (AGVTOOL + plist + pubspec)
        script: |
          set -euo pipefail

          BUILD_NUMBER="$(date -u +%Y%m%d%H%M%S)"
          echo "FORCING BUILD_NAME=$BUILD_NAME"
          echo "FORCING BUILD_NUMBER=$BUILD_NUMBER"

          echo "BUILD_NUMBER=$BUILD_NUMBER" >> "$CM_ENV"

          perl -0777 -i -pe 's/^version:\s*.+$/version: '"$BUILD_NAME"'+'"$BUILD_NUMBER"'/m' pubspec.yaml
          echo "pubspec version now:"
          grep '^version:' pubspec.yaml || true

          cd ios
          agvtool new-version -all "$BUILD_NUMBER"
          agvtool new-marketing-version "$BUILD_NAME"
          cd ..

          PLIST="ios/Runner/Info.plist"
          /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $BUILD_NAME" "$PLIST" 2>/dev/null \
            || /usr/libexec/PlistBuddy -c "Add :CFBundleShortVersionString string $BUILD_NAME" "$PLIST"
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" "$PLIST" 2>/dev/null \
            || /usr/libexec/PlistBuddy -c "Add :CFBundleVersion string $BUILD_NUMBER" "$PLIST"

          echo "Info.plist now:"
          /usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "$PLIST"
          /usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "$PLIST"

      - name: Set up code signing settings on Xcode project
        script: |
          set -euo pipefail
          xcode-project use-profiles --project ios/Runner.xcodeproj --archive-method app-store
          echo "export_options.plist:"
          ls -la "$HOME/export_options.plist" || true

      - name: Build IPA
        script: |
          set -euo pipefail

          flutter clean
          flutter pub get

          if [ -f "$HOME/export_options.plist" ]; then
            flutter build ipa --export-options-plist="$HOME/export_options.plist"
          else
            flutter build ipa
          fi

          ls -la build/ios/ipa || true
          ls -la build/ios/ipa/*.ipa || true

      - name: Upload IPA to App Store Connect (TestFlight)
        script: |
          set -euo pipefail

          IPA_PATH="$(ls -1 build/ios/ipa/*.ipa | head -n 1)"
          echo "Uploading: $IPA_PATH"

          app-store-connect publish \
            --path "$IPA_PATH" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --private-key @file:$HOME/AuthKey.p8

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

  android-workflow:
    name: Android Workflow
    max_build_duration: 60

    environment:
      flutter: stable
      java: 17

      android_signing:
        - pannasignals_keystore

      groups:
        - google_play

      vars:
        PACKAGE_NAME: "com.panna.signalsApp"
        BUILD_NAME: "1.0.2"
        BUILD_NUMBER: "4"

    scripts:
      - name: Set up key.properties
        script: |
          echo "storePassword=pannaSignals2024" > $CM_BUILD_DIR/android/key.properties
          echo "keyPassword=pannaSignals2024" >> $CM_BUILD_DIR/android/key.properties
          echo "keyAlias=upload" >> $CM_BUILD_DIR/android/key.properties
          echo "storeFile=$CM_KEYSTORE_PATH" >> $CM_BUILD_DIR/android/key.properties

      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Build AAB
        script: |
          flutter clean
          flutter build appbundle --release \
            --build-name=$BUILD_NAME \
            --build-number=$BUILD_NUMBER

    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log

    publishing:
      email:
        recipients:
          - driton.mahmudi@gmail.com
        notify:
          success: true
          failure: true

      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true
